export const matt = [
  "We Love Matt!",
  "Matt is Awesome!",
  "Matt is the Best!",
  "All hail Matt!",
  "Matt is sooo Amazing!",
  "Matt is Astounding!",
  "Matt is Astonishing!",
  "Matt is Remarkable!",
  "Matt is Spectacular!",
  "Matt is Incredible!",
  "Matt is Extraordinary!",
  "Matt is Sensational!",
  "Matt is Marvellous!",
  "Matt is a Genius!",
  "Matt is Wonderful!",
  "Matt is Majestic!",
  "Matt is Mind-blowing!",
  "Matt is Thrilling!",
  "Matt is Fantastic!",
  "Matt is Terrific!",
  "Matt is Epic!",
  "Matt is Pog!",
  "Legend has it that when Matt looks you in the eyes, you see the universe.",
  "Legend has it that when Matt walks in a room, music starts playing.",
  "Legend has it that when Matt snaps his fingers, all bugs disappear.",
  "Matt is soo Cool!",
  "Matt is a Hero!",
  "Matt is a Star!",
  "Matt is Legendary!",
  "Matt is 11/10!",
  "Matt is Superb!",
  "Matt is Wholesome!",
  "Be like Matt, be Amazing",
  "Matt does everything so well!",
  "We all aspire to be Matt!",
  "Everything is Matt-tastic!",
  "Matt is a gift to those around him.",
  "Matt is the smartest cookie!",
  "Everything would be better if more people were like Matt!",
  "Matt (noun): An amazing person!",
  "Matt (noun): An Astonishing person!",
  "Matt (noun): A Remarkable person!",
  "Matt (noun): A Spectacular person!",
  "Matt (noun): An Incredible person!",
  "Matt (noun): An Extraordinary person!",
  "Matt (noun): A Sensational person!",
  "Matt (noun): A Marvelous person!",
  "Matt (noun): A Wonderful person!",
  "Matt (noun): A Thrilling person!",
  "Matt (noun): A Fantastic person!",
  "Matt (noun): A Terrific person!",
  "M.A.T.T (acronym): Majestic Awesome Talented Trendy",
];
export const raven = [
  "We Love Raven!",
  "Raven is Awesome!",
  "Raven is the Best!",
  "All hail Raven!",
  "Raven is sooo Amazing!",
  "Raven is Astounding!",
  "Raven is Astonishing!",
  "Raven is Remarkable!",
  "Raven is Spectacular!",
  "Raven is Incredible!",
  "Raven is Extraordinary!",
  "Raven is Sensational!",
  "Raven is Marvellous!",
  "Raven is a Genius!",
  "Raven is Wonderful!",
  "Raven is Majestic!",
  "Raven is Mind-blowing!",
  "Raven is Thrilling!",
  "Raven is Fantastic!",
  "Raven is Terrific!",
  "Raven is Epic!",
  "Raven is Pog!",
  "Legend has it that when Raven looks you in the eyes, you see the universe.",
  "Legend has it that when Raven walks in a room, music starts playing.",
  "Legend has it that when Raven snaps his fingers, all bugs disappear.",
  "Raven is soo Cool!",
  "Raven is a Hero!",
  "Raven is a Star!",
  "Raven is Legendary!",
  "Raven is 11/10!",
  "Raven is Superb!",
  "Raven is Wholesome!",
  "Be like Raven, be Amazing",
  "Raven does everything so well!",
  "We all aspire to be Raven!",
  "Raven (noun): An amazing person!",
  "Raven (noun): An Astonishing person!",
  "Raven (noun): A Remarkable person!",
  "Raven (noun): A Spectacular person!",
  "Raven (noun): An Incredible person!",
  "Raven (noun): An Extraordinary person!",
  "Raven (noun): A Sensational person!",
  "Raven (noun): A Marvelous person!",
  "Raven (noun): A Wonderful person!",
  "Raven (noun): A Thrilling person!",
  "Raven (noun): A Fantastic person!",
  "Raven (noun): A Terrific person!",
];
export const luke = [
  "We Love Luke!",
  "Luke is Awesome!",
  "Luke is the Best!",
  "All hail Luke!",
  "Luke is sooo Amazing!",
  "Luke is Astounding!",
  "Luke is Astonishing!",
  "Luke is Remarkable!",
  "Luke is Spectacular!",
  "Luke is Incredible!",
  "Luke is Extraordinary!",
  "Luke is Sensational!",
  "Luke is Marvellous!",
  "Luke is a Genius!",
  "Luke is Wonderful!",
  "Luke is Majestic!",
  "Luke is Mind-blowing!",
  "Luke is Thrilling!",
  "Luke is Fantastic!",
  "Luke is Terrific!",
  "Luke is Epic!",
  "Luke is Pog!",
  "Luke, how do you keep being so funny and making everyone laugh?",
  "Legend has it that when Luke looks you in the eyes, you see the universe.",
  "Legend has it that when Luke walks in a room, music starts playing.",
  "Legend has it that when Luke snaps his fingers, all bugs disappear.",
  "Jokes are funnier when Luke tells them.",
  "Luke is soo Cool!",
  "Luke is a Hero!",
  "Luke is a Star!",
  "Luke is Legendary!",
  "Luke is 11/10!",
  "Luke is Superb!",
  "Luke is Wholesome!",
  "Be like Luke, be Amazing",
  "Luke does everything so well!",
  "We all aspire to be Luke!",
  "Luke (noun): An amazing person!",
  "Luke (noun): An Astonishing person!",
  "Luke (noun): A Remarkable person!",
  "Luke (noun): A Spectacular person!",
  "Luke (noun): An Incredible person!",
  "Luke (noun): An Extraordinary person!",
  "Luke (noun): A Sensational person!",
  "Luke (noun): A Marvelous person!",
  "Luke (noun): A Wonderful person!",
  "Luke (noun): A Thrilling person!",
  "Luke (noun): A Fantastic person!",
  "Luke (noun): A Terrific person!",
];
export const nick = [
  "We Love Nicholas!",
  "Nicholas is Awesome!",
  "Nicholas is the Best!",
  "All hail Nicholas!",
  "Nicholas is sooo Amazing!",
  "Nicholas is Astounding!",
  "Nicholas is Astonishing!",
  "Nicholas is Remarkable!",
  "Nicholas is Spectacular!",
  "Nicholas is Incredible!",
  "Nicholas is Extraordinary!",
  "Nicholas is Sensational!",
  "Nicholas is Marvellous!",
  "Nicholas is a Genius!",
  "Nicholas is Wonderful!",
  "Nicholas is Majestic!",
  "Nicholas is Mind-blowing!",
  "Nicholas is Thrilling!",
  "Nicholas is Fantastic!",
  "Nicholas is Terrific!",
  "Nicholas is Epic!",
  "Nicholas is Pog!",
  "Legend has it that when Nicholas looks you in the eyes, you see the universe.",
  "Legend has it that when Nicholas walks in a room, music starts playing.",
  "Legend has it that when Nicholas snaps his fingers, all bugs disappear.",
  "Nicholas is soo Cool!",
  "Nicholas is a Hero!",
  "Nicholas is a Star!",
  "Nicholas is Legendary!",
  "Nicholas is 11/10!",
  "Nicholas is Superb!",
  "Nicholas is Wholesome!",
  "Be like Nicholas, be Amazing",
  "Nicholas does everything so well!",
  "We all aspire to be Nicholas!",
  "Nicholas (noun): An amazing person!",
  "Nicholas (noun): An Astonishing person!",
  "Nicholas (noun): A Remarkable person!",
  "Nicholas (noun): A Spectacular person!",
  "Nicholas (noun): An Incredible person!",
  "Nicholas (noun): An Extraordinary person!",
  "Nicholas (noun): A Sensational person!",
  "Nicholas (noun): A Marvelous person!",
  "Nicholas (noun): A Wonderful person!",
  "Nicholas (noun): A Thrilling person!",
  "Nicholas (noun): A Fantastic person!",
  "Nicholas (noun): A Terrific person!",
];
export const daniel = [
  "We Love Daniel!",
  "Daniel is Awesome!",
  "Daniel is the Best!",
  "All hail Daniel!",
  "Daniel is sooo Amazing!",
  "Daniel is Astounding!",
  "Daniel is Astonishing!",
  "Daniel is Remarkable!",
  "Daniel is Spectacular!",
  "Daniel is Incredible!",
  "Daniel is Extraordinary!",
  "Daniel is Sensational!",
  "Daniel is Marvellous!",
  "Daniel is a Genius!",
  "Daniel is Wonderful!",
  "Daniel is Majestic!",
  "Daniel is Mind-blowing!",
  "Daniel is Thrilling!",
  "Daniel is Fantastic!",
  "Daniel is Terrific!",
  "Daniel is Epic!",
  "Legend has it that when Daniel looks you in the eyes, you see the universe.",
  "Legend has it that when Daniel walks in a room, music starts playing.",
  "Legend has it that when Daniel snaps his fingers, all bugs disappear.",
  "Daniel is soo Cool!",
  "Daniel is a Hero!",
  "Daniel is a Star!",
  "Daniel is Legendary!",
  "Daniel is 11/10!",
  "Daniel is Superb!",
  "Daniel is Wholesome!",
  "Be like Daniel, be Amazing",
  "Daniel does everything so well!",
  "We all aspire to be Daniel!",
  "Everything is Dan-tastic!",
  "Daniel (noun): An amazing person!",
  "Daniel (noun): An Astonishing person!",
  "Daniel (noun): A Remarkable person!",
  "Daniel (noun): A Spectacular person!",
  "Daniel (noun): An Incredible person!",
  "Daniel (noun): An Extraordinary person!",
  "Daniel (noun): A Sensational person!",
  "Daniel (noun): A Marvelous person!",
  "Daniel (noun): A Wonderful person!",
  "Daniel (noun): A Thrilling person!",
  "Daniel (noun): A Fantastic person!",
  "Daniel (noun): A Terrific person!",
];
export const hacktoberfest = [
  "We Love Hacktoberfest!",
  "Hacktoberfest is Awesome!",
  "Hacktoberfest is the Best!",
  "Hacktoberfest is sooo Amazing!",
  "Hacktoberfest is sooo fun!",
  "Hacktoberfest is Spectacular!",
  "Hacktoberfest is Incredible!",
  "Hacktoberfest is Extraordinary!",
  "Hacktoberfest is Sensational!",
  "Hacktoberfest is Marvellous!",
  "Hacktoberfest is Wonderful!",
  "Hacktoberfest is intoxicatingly amazing",
  "Hacktoberfest is Mind-blowing!",
  "Hacktoberfest is Thrilling!",
  "Hacktoberfest is Fantastic!",
  "Hacktoberfest is Terrific!",
  "Legend has it that when you submit 150 PRs, you find the secret to be as epic as the HacktoberFest Team.",
  "Legend has it that when you participate in hacktoberfest, all troubles disappear.",
  "Hacktoberfest is Epic!",
  "Hacktoberfest is soo Cool!",
  "Hacktoberfest is Legendary!",
  "Hacktoberfest is 3000/10!",
  "Hacktoberfest is Superb!",
  "Hacktoberfest is :heart:",
  "Hacktoberfest is really something special.",
  "Hacktoberfest, we're grateful to have known about you.",
  "Hacktoberfest is  like a ray of sunshine on a really dreary day.",
  "Hacktoberfest makes the world a better place.",
  "Hacktoberfest team is Wholesome!",
  "Hacktoberfest is love, OpenSource is life...",
  "The HacktoberFest team is very wholesome and helpful.",
  "Be like Hacktoberfest team, be Amazing",
  "Hacktoberfest Team is the Best!",
  "Hacktoberfest Team is sooo Amazing!",
  "Hacktoberfest Team is sooo fun!",
  "Hacktoberfest Team is Spectacular!",
  "Hacktoberfest Team is Incredible!",
  "Hacktoberfest Team is Extraordinary!",
  "Hacktoberfest Team is Sensational!",
  "Hacktoberfest Team is Marvellous!",
  "Hacktoberfest Team is Wonderful!",
  "Hacktoberfest Team is Mind-blowing!",
  "Hacktoberfest Team is Thrilling!",
  "Hacktoberfest Team is Fantastic!",
  "Hacktoberfest Team is Terrific!",
  "Hacktoberfest team always makes us feel welcomed :heart:",
  "Hacktoberfest team is amazing",
  "When Hacktoberfest Team says they will do something, We trust them. :heart:",
  "Hacktoberfest team does everything so well!",
  "We all aspire to be like Hacktoberfest team members!",
  "Hacktoberfest (noun): An amazing event!",
  "Hacktoberfest (noun): A Spectacular event!",
  "Hacktoberfest (noun): An amazing team",
  "Hacktoberfest Team (noun): An Incredible team!",
  "Hacktoberfest Team (noun): An Extraordinary Team!",
  "Hacktoberfest Team (noun): A Marvelous Team!",
  "Hacktoberfest Team (noun): A team better than the Avengers",
  "Hacktoberfest Team (noun): A bunch of very smart and very good people",
];
export const ocean = [
  "We Love DigitalOcean!",
  "DigitalOcean is Awesome!",
  "DigitalOcean is the Best!",
  "DigitalOcean is sooo Amazing!",
  "DigitalOcean is Sensational!",
  "DigitalOcean is Marvellous!",
  "DigitalOcean is Wonderful!",
  "DigitalOcean is Fantastic!",
  "DigitalOcean team is Epic!",
  "DigitalOcean team is soo Cool!",
  "DigitalOcean is 11/10!",
  "DigitalOcean is :heart:",
  "DigitalOcean makes the world a better place.",
  "Be like DigitalOcean's Cloud, be Amazing",
  "DigitalOcean is the Best!",
  "DigitalOcean (noun): Simple and scalable cloud platform",
  "DigitalOcean (noun): Amazing company",
];
export const vonage = [
  "We Love Vonage!",
  "Vonage is Awesome!",
  "Vonage team is so nice",
  "Vonage team is amazing",
  "We love working on Vonage projects",
  "We love attending Vonage twitch streams",
  "Vonage is 11/10!",
  "Vonage is :vonageheart:",
  "Vonage makes the world a better place.",
  "Be like Vonage's communication APIs, be Amazing",
  "Vonage team is the Best!",
  "Vonage (noun): Customer Experience haven",
  "Vonage (noun): Amazing company",
];
export const ben = [
  "We Love Diana!",
  "Diana is Awesome!",
  "Diana is the Best!",
  "All hail Diana!",
  "Diana is sooo Amazing!",
  "Diana is Astounding!",
  "Diana is Astonishing!",
  "Diana is Remarkable!",
  "Diana is Spectacular!",
  "Diana is Incredible!",
  "Diana is Extraordinary!",
  "Diana is Sensational!",
  "Diana is Marvellous!",
  "Diana is a Genius!",
  "Diana is Wonderful!",
  "Diana is Majestic!",
  "Diana is Mind-blowing!",
  "Diana is Thrilling!",
  "Diana is Fantastic!",
  "Diana is Terrific!",
  "Diana is Epic!",
  "Legend has it that when Diana looks you in the eyes, you see the universe.",
  "Legend has it that when Diana walks in a room, music starts playing.",
  "Legend has it that when Diana snaps his fingers, all bugs disappear.",
  "Diana is soo Cool!",
  "Diana is a Hero!",
  "Diana is a Star!",
  "Diana is Legendary!",
  "Diana is 11/10!",
  "Diana is Superb!",
  "Diana is Wholesome!",
  "Be like Diana, be Amazing",
  "Diana does everything so well!",
  "We all aspire to be Diana!",
  "Diana (noun): An amazing person!",
  "Diana (noun): An Astonishing person!",
  "Diana (noun): A Remarkable person!",
  "Diana (noun): A Spectacular person!",
  "Diana (noun): An Incredible person!",
  "Diana (noun): An Extraordinary person!",
  "Diana (noun): A Sensational person!",
  "Diana (noun): A Marvelous person!",
  "Diana (noun): A Wonderful person!",
  "Diana (noun): A Thrilling person!",
  "Diana (noun): A Fantastic person!",
  "Diana (noun): A Terrific person!",
];
export const diana = [
  "We Love Diana!",
  "Diana is Awesome!",
  "Diana is the Best!",
  "All hail Diana!",
  "Diana is sooo Amazing!",
  "Diana is Astounding!",
  "Diana is Astonishing!",
  "Diana is Remarkable!",
  "Diana is Spectacular!",
  "Diana is Incredible!",
  "Diana is Extraordinary!",
  "Diana is Sensational!",
  "Diana is Marvellous!",
  "Diana is a Genius!",
  "Diana is Wonderful!",
  "Diana is Majestic!",
  "Diana is Mind-blowing!",
  "Diana is Thrilling!",
  "Diana is Fantastic!",
  "Diana is Terrific!",
  "Diana is Epic!",
  "Legend has it that when Diana looks you in the eyes, you see the universe.",
  "Legend has it that when Diana walks in a room, music starts playing.",
  "Legend has it that when Diana snaps her fingers, all bugs disappear.",
  "Diana is soo Cool!",
  "Diana is a Hero!",
  "Diana is a Star!",
  "Diana is Legendary!",
  "Diana is 11/10!",
  "Diana is Superb!",
  "Diana is Wholesome!",
  "Be like Diana, be Amazing",
  "Diana does everything so well!",
  "We all aspire to be Diana!",
  "Diana (noun): An amazing person!",
  "Diana (noun): An Astonishing person!",
  "Diana (noun): A Remarkable person!",
  "Diana (noun): A Spectacular person!",
  "Diana (noun): An Incredible person!",
  "Diana (noun): An Extraordinary person!",
  "Diana (noun): A Sensational person!",
  "Diana (noun): A Marvelous person!",
  "Diana (noun): A Wonderful person!",
  "Diana (noun): A Thrilling person!",
  "Diana (noun): A Fantastic person!",
  "Diana (noun): A Terrific person!",
];
