export const matt = [
  "We Love Matt!",
  "Matt is Awesome!",
  "Matt is the Best!",
  "All hail Matt!",
  "Matt is sooo Amazing!",
  "Matt is Astounding!",
  "Matt is Astonishing!",
  "Matt is Remarkable!",
  "Matt is Spectacular!",
  "Matt is Incredible!",
  "Matt is Extraordinary!",
  "Matt is Sensational!",
  "Matt is Marvellous!",
  "Matt is a Genius!",
  "Matt is Wonderful!",
  "Matt is Majestic!",
  "Matt is Mind-blowing!",
  "Matt is Thrilling!",
  "Matt is Fantastic!",
  "Matt is Terrific!",
  "Matt is Epic!",
  "Matt is Pog!",
  "Legend has it that when Matt looks you in the eyes, you see the universe.",
  "Legend has it that when Matt walks in a room, music starts playing.",
  "Legend has it that when Matt snaps his fingers, all bugs disappear.",
  "Matt is soo Cool!",
  "Matt is a Hero!",
  "Matt is a Star!",
  "Matt is Legendary!",
  "Matt is 11/10!",
  "Matt is Superb!",
  "Matt is Wholesome!",
  "Be like Matt, be Amazing",
  "Matt does everything so well!",
  "We all aspire to be Matt!",
  "Everything is Matt-tastic!",
  "Matt (noun): An amazing person!",
  "Matt (noun): An Astonishing person!",
  "Matt (noun): A Remarkable person!",
  "Matt (noun): A Spectacular person!",
  "Matt (noun): An Incredible person!",
  "Matt (noun): An Extraordinary person!",
  "Matt (noun): A Sensational person!",
  "Matt (noun): A Marvelous person!",
  "Matt (noun): A Wonderful person!",
  "Matt (noun): A Thrilling person!",
  "Matt (noun): A Fantastic person!",
  "Matt (noun): A Terrific person!",
  "M.A.T.T (acronym): Majestic Awesome Talented Trendy",
];
export const raven = [
  "We Love Raven!",
  "Raven is Awesome!",
  "Raven is the Best!",
  "All hail Raven!",
  "Raven is sooo Amazing!",
  "Raven is Astounding!",
  "Raven is Astonishing!",
  "Raven is Remarkable!",
  "Raven is Spectacular!",
  "Raven is Incredible!",
  "Raven is Extraordinary!",
  "Raven is Sensational!",
  "Raven is Marvellous!",
  "Raven is a Genius!",
  "Raven is Wonderful!",
  "Raven is Majestic!",
  "Raven is Mind-blowing!",
  "Raven is Thrilling!",
  "Raven is Fantastic!",
  "Raven is Terrific!",
  "Raven is Epic!",
  "Raven is Pog!",
  "Legend has it that when Raven looks you in the eyes, you see the universe.",
  "Legend has it that when Raven walks in a room, music starts playing.",
  "Legend has it that when Raven snaps his fingers, all bugs disappear.",
  "Raven is soo Cool!",
  "Raven is a Hero!",
  "Raven is a Star!",
  "Raven is Legendary!",
  "Raven is 11/10!",
  "Raven is Superb!",
  "Raven is Wholesome!",
  "Be like Raven, be Amazing",
  "Raven does everything so well!",
  "We all aspire to be Raven!",
  "Raven (noun): An amazing person!",
  "Raven (noun): An Astonishing person!",
  "Raven (noun): A Remarkable person!",
  "Raven (noun): A Spectacular person!",
  "Raven (noun): An Incredible person!",
  "Raven (noun): An Extraordinary person!",
  "Raven (noun): A Sensational person!",
  "Raven (noun): A Marvelous person!",
  "Raven (noun): A Wonderful person!",
  "Raven (noun): A Thrilling person!",
  "Raven (noun): A Fantastic person!",
  "Raven (noun): A Terrific person!",
];
export const luke = [
  "We Love Luke!",
  "Luke is Awesome!",
  "Luke is the Best!",
  "All hail Luke!",
  "Luke is sooo Amazing!",
  "Luke is Astounding!",
  "Luke is Astonishing!",
  "Luke is Remarkable!",
  "Luke is Spectacular!",
  "Luke is Incredible!",
  "Luke is Extraordinary!",
  "Luke is Sensational!",
  "Luke is Marvellous!",
  "Luke is a Genius!",
  "Luke is Wonderful!",
  "Luke is Majestic!",
  "Luke is Mind-blowing!",
  "Luke is Thrilling!",
  "Luke is Fantastic!",
  "Luke is Terrific!",
  "Luke is Epic!",
  "Luke is Pog!",
  "Legend has it that when Luke looks you in the eyes, you see the universe.",
  "Legend has it that when Luke walks in a room, music starts playing.",
  "Legend has it that when Luke snaps his fingers, all bugs disappear.",
  "Luke is soo Cool!",
  "Luke is a Hero!",
  "Luke is a Star!",
  "Luke is Legendary!",
  "Luke is 11/10!",
  "Luke is Superb!",
  "Luke is Wholesome!",
  "Be like Luke, be Amazing",
  "Luke does everything so well!",
  "We all aspire to be Luke!",
  "Luke (noun): An amazing person!",
  "Luke (noun): An Astonishing person!",
  "Luke (noun): A Remarkable person!",
  "Luke (noun): A Spectacular person!",
  "Luke (noun): An Incredible person!",
  "Luke (noun): An Extraordinary person!",
  "Luke (noun): A Sensational person!",
  "Luke (noun): A Marvelous person!",
  "Luke (noun): A Wonderful person!",
  "Luke (noun): A Thrilling person!",
  "Luke (noun): A Fantastic person!",
  "Luke (noun): A Terrific person!",
];
export const nick = [
  "We Love Nicholas!",
  "Nicholas is Awesome!",
  "Nicholas is the Best!",
  "All hail Nicholas!",
  "Nicholas is sooo Amazing!",
  "Nicholas is Astounding!",
  "Nicholas is Astonishing!",
  "Nicholas is Remarkable!",
  "Nicholas is Spectacular!",
  "Nicholas is Incredible!",
  "Nicholas is Extraordinary!",
  "Nicholas is Sensational!",
  "Nicholas is Marvellous!",
  "Nicholas is a Genius!",
  "Nicholas is Wonderful!",
  "Nicholas is Majestic!",
  "Nicholas is Mind-blowing!",
  "Nicholas is Thrilling!",
  "Nicholas is Fantastic!",
  "Nicholas is Terrific!",
  "Nicholas is Epic!",
  "Nicholas is Pog!",
  "Legend has it that when Nicholas looks you in the eyes, you see the universe.",
  "Legend has it that when Nicholas walks in a room, music starts playing.",
  "Legend has it that when Nicholas snaps his fingers, all bugs disappear.",
  "Nicholas is soo Cool!",
  "Nicholas is a Hero!",
  "Nicholas is a Star!",
  "Nicholas is Legendary!",
  "Nicholas is 11/10!",
  "Nicholas is Superb!",
  "Nicholas is Wholesome!",
  "Be like Nicholas, be Amazing",
  "Nicholas does everything so well!",
  "We all aspire to be Nicholas!",
  "Nicholas (noun): An amazing person!",
  "Nicholas (noun): An Astonishing person!",
  "Nicholas (noun): A Remarkable person!",
  "Nicholas (noun): A Spectacular person!",
  "Nicholas (noun): An Incredible person!",
  "Nicholas (noun): An Extraordinary person!",
  "Nicholas (noun): A Sensational person!",
  "Nicholas (noun): A Marvelous person!",
  "Nicholas (noun): A Wonderful person!",
  "Nicholas (noun): A Thrilling person!",
  "Nicholas (noun): A Fantastic person!",
  "Nicholas (noun): A Terrific person!",
];
export const daniel = [
  "We Love Daniel!",
  "Daniel is Awesome!",
  "Daniel is the Best!",
  "All hail Daniel!",
  "Daniel is sooo Amazing!",
  "Daniel is Astounding!",
  "Daniel is Astonishing!",
  "Daniel is Remarkable!",
  "Daniel is Spectacular!",
  "Daniel is Incredible!",
  "Daniel is Extraordinary!",
  "Daniel is Sensational!",
  "Daniel is Marvellous!",
  "Daniel is a Genius!",
  "Daniel is Wonderful!",
  "Daniel is Majestic!",
  "Daniel is Mind-blowing!",
  "Daniel is Thrilling!",
  "Daniel is Fantastic!",
  "Daniel is Terrific!",
  "Daniel is Epic!",
  "Legend has it that when Daniel looks you in the eyes, you see the universe.",
  "Legend has it that when Daniel walks in a room, music starts playing.",
  "Legend has it that when Daniel snaps his fingers, all bugs disappear.",
  "Daniel is soo Cool!",
  "Daniel is a Hero!",
  "Daniel is a Star!",
  "Daniel is Legendary!",
  "Daniel is 11/10!",
  "Daniel is Superb!",
  "Daniel is Wholesome!",
  "Be like Daniel, be Amazing",
  "Daniel does everything so well!",
  "We all aspire to be Daniel!",
  "Everything is Dan-tastic!",
  "Daniel (noun): An amazing person!",
  "Daniel (noun): An Astonishing person!",
  "Daniel (noun): A Remarkable person!",
  "Daniel (noun): A Spectacular person!",
  "Daniel (noun): An Incredible person!",
  "Daniel (noun): An Extraordinary person!",
  "Daniel (noun): A Sensational person!",
  "Daniel (noun): A Marvelous person!",
  "Daniel (noun): A Wonderful person!",
  "Daniel (noun): A Thrilling person!",
  "Daniel (noun): A Fantastic person!",
  "Daniel (noun): A Terrific person!",
];
